"""schema inicial (fases 1-17)

Revision ID: 6e470dce13c0
Revises:
Create Date: 2026-07-29 01:54:03.705310

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6e470dce13c0"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "api_keys",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("nome", sa.String(length=100), nullable=False),
        sa.Column("key_hash", sa.String(length=64), nullable=False),
        sa.Column("prefixo", sa.String(length=11), nullable=False),
        sa.Column("ativo", sa.Boolean(), nullable=False),
        sa.Column("criado_em", sa.DateTime(), nullable=False),
        sa.Column("expira_em", sa.DateTime(), nullable=True),
        sa.Column("ultimo_uso", sa.DateTime(), nullable=True),
        sa.Column("total_requisicoes", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("api_keys", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_api_keys_key_hash"), ["key_hash"], unique=True)

    op.create_table(
        "async_jobs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("tipo", sa.String(length=50), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("progresso", sa.Float(), nullable=False),
        sa.Column("parametros", sa.Text(), nullable=True),
        sa.Column("resultado", sa.Text(), nullable=True),
        sa.Column("erro", sa.Text(), nullable=True),
        sa.Column("mensagem", sa.String(length=500), nullable=True),
        sa.Column("criado_em", sa.DateTime(), nullable=False),
        sa.Column("concluido_em", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("async_jobs", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_async_jobs_criado_em"), ["criado_em"], unique=False)
        batch_op.create_index(batch_op.f("ix_async_jobs_status"), ["status"], unique=False)
        batch_op.create_index(batch_op.f("ix_async_jobs_tipo"), ["tipo"], unique=False)

    op.create_table(
        "audit_logs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("usuario_id", sa.Integer(), nullable=True),
        sa.Column("usuario_email", sa.String(length=255), nullable=True),
        sa.Column("api_key_id", sa.Integer(), nullable=True),
        sa.Column("acao", sa.String(length=100), nullable=False),
        sa.Column("recurso", sa.String(length=255), nullable=False),
        sa.Column("metodo", sa.String(length=10), nullable=True),
        sa.Column("ip", sa.String(length=45), nullable=True),
        sa.Column("status_code", sa.Integer(), nullable=True),
        sa.Column("detalhes", sa.Text(), nullable=True),
        sa.Column("criado_em", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("audit_logs", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_audit_logs_acao"), ["acao"], unique=False)
        batch_op.create_index(batch_op.f("ix_audit_logs_api_key_id"), ["api_key_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_audit_logs_criado_em"), ["criado_em"], unique=False)
        batch_op.create_index(batch_op.f("ix_audit_logs_usuario_id"), ["usuario_id"], unique=False)

    op.create_table(
        "escritorios",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("nome", sa.String(length=150), nullable=False),
        sa.Column("slug", sa.String(length=50), nullable=False),
        sa.Column("cnpj", sa.String(length=14), nullable=True),
        sa.Column("ativo", sa.Boolean(), nullable=False),
        sa.Column("criado_em", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("escritorios", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_escritorios_slug"), ["slug"], unique=True)

    op.create_table(
        "filter_views",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("nome", sa.String(length=100), nullable=False),
        sa.Column("criterios_json", sa.Text(), nullable=False),
        sa.Column("criado_em", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "webhooks",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("url", sa.String(length=2048), nullable=False),
        sa.Column("eventos", sa.Text(), nullable=False),
        sa.Column("secret", sa.String(length=128), nullable=True),
        sa.Column("descricao", sa.String(length=255), nullable=False),
        sa.Column("ativo", sa.Boolean(), nullable=False),
        sa.Column("max_retries", sa.Integer(), nullable=False),
        sa.Column("criado_em", sa.DateTime(), nullable=False),
        sa.Column("ultimo_envio", sa.DateTime(), nullable=True),
        sa.Column("total_envios", sa.Integer(), nullable=False),
        sa.Column("total_falhas", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "empresas",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("cnpj", sa.String(length=14), nullable=False),
        sa.Column("nome", sa.String(length=150), nullable=False),
        sa.Column("uf", sa.String(length=2), nullable=True),
        sa.Column("ie", sa.String(length=14), nullable=True),
        sa.Column("cod_mun", sa.String(length=7), nullable=True),
        sa.Column("im", sa.String(length=14), nullable=True),
        sa.Column("ind_sit_esp", sa.Integer(), nullable=True),
        sa.Column("ind_nire", sa.Integer(), nullable=True),
        sa.Column("ind_fin_esc", sa.Integer(), nullable=True),
        sa.Column("ind_grande_por", sa.Integer(), nullable=True),
        sa.Column("tip_ecd", sa.String(length=1), nullable=True),
        sa.Column("ident_mf", sa.String(length=1), nullable=True),
        sa.Column("ind_esc_cons", sa.String(length=1), nullable=True),
        sa.Column("escritorio_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["escritorio_id"],
            ["escritorios.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("empresas", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_empresas_cnpj"), ["cnpj"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_empresas_escritorio_id"), ["escritorio_id"], unique=False
        )

    op.create_table(
        "rate_limit_configs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("api_key_id", sa.Integer(), nullable=False),
        sa.Column("limite", sa.Integer(), nullable=False),
        sa.Column("janela", sa.Integer(), nullable=False),
        sa.Column("criado_em", sa.DateTime(), nullable=False),
        sa.Column("atualizado_em", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["api_key_id"],
            ["api_keys.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("rate_limit_configs", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_rate_limit_configs_api_key_id"), ["api_key_id"], unique=True
        )

    op.create_table(
        "usuarios",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("nome", sa.String(length=150), nullable=False),
        sa.Column("senha_hash", sa.String(length=128), nullable=False),
        sa.Column("salt", sa.String(length=64), nullable=False),
        sa.Column("ativo", sa.Boolean(), nullable=False),
        sa.Column("admin", sa.Boolean(), nullable=False),
        sa.Column("escritorio_id", sa.Integer(), nullable=True),
        sa.Column("criado_em", sa.DateTime(), nullable=False),
        sa.Column("ultimo_login", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["escritorio_id"],
            ["escritorios.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("usuarios", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_usuarios_email"), ["email"], unique=True)
        batch_op.create_index(
            batch_op.f("ix_usuarios_escritorio_id"), ["escritorio_id"], unique=False
        )

    op.create_table(
        "webhook_deliveries",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("webhook_id", sa.Integer(), nullable=False),
        sa.Column("evento", sa.String(length=50), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("status_code", sa.Integer(), nullable=True),
        sa.Column("request_body", sa.Text(), nullable=True),
        sa.Column("response_body", sa.Text(), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("tentativa", sa.Integer(), nullable=False),
        sa.Column("criado_em", sa.DateTime(), nullable=False),
        sa.Column("concluido_em", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["webhook_id"],
            ["webhooks.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("webhook_deliveries", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_webhook_deliveries_evento"), ["evento"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_webhook_deliveries_webhook_id"), ["webhook_id"], unique=False
        )

    op.create_table(
        "ecds",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("empresa_id", sa.Integer(), nullable=False),
        sa.Column("leiaute", sa.String(length=3), nullable=False),
        sa.Column("dt_ini", sa.Date(), nullable=False),
        sa.Column("dt_fin", sa.Date(), nullable=False),
        sa.Column("ind_esc", sa.String(length=1), nullable=True),
        sa.Column("cod_ver_lc", sa.String(length=3), nullable=True),
        sa.Column("hash_arquivo", sa.String(length=64), nullable=True),
        sa.Column("nome_arquivo", sa.String(length=255), nullable=True),
        sa.Column("importado_em", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["empresa_id"],
            ["empresas.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("empresa_id", "dt_ini", "dt_fin", name="uq_ecd_empresa_periodo"),
    )
    with op.batch_alter_table("ecds", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_ecds_empresa_id"), ["empresa_id"], unique=False)

    op.create_table(
        "mapeamentos",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("empresa_id", sa.Integer(), nullable=False),
        sa.Column("tipo", sa.String(length=20), nullable=False),
        sa.Column("cod_cta", sa.String(length=255), nullable=False),
        sa.Column("categoria", sa.String(length=100), nullable=False),
        sa.Column("ordem", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["empresa_id"],
            ["empresas.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("empresa_id", "tipo", "cod_cta", name="uq_mapeamento"),
    )
    with op.batch_alter_table("mapeamentos", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_mapeamentos_empresa_id"), ["empresa_id"], unique=False)

    op.create_table(
        "sessoes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("usuario_id", sa.Integer(), nullable=False),
        sa.Column("token", sa.String(length=128), nullable=False),
        sa.Column("criado_em", sa.DateTime(), nullable=False),
        sa.Column("expira_em", sa.DateTime(), nullable=False),
        sa.Column("ip", sa.String(length=45), nullable=True),
        sa.Column("user_agent", sa.String(length=512), nullable=True),
        sa.ForeignKeyConstraint(
            ["usuario_id"],
            ["usuarios.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("sessoes", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_sessoes_token"), ["token"], unique=True)
        batch_op.create_index(batch_op.f("ix_sessoes_usuario_id"), ["usuario_id"], unique=False)

    op.create_table(
        "usuarios_empresas",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("usuario_id", sa.Integer(), nullable=False),
        sa.Column("empresa_id", sa.Integer(), nullable=False),
        sa.Column("permissao", sa.String(length=20), nullable=False),
        sa.ForeignKeyConstraint(
            ["empresa_id"],
            ["empresas.id"],
        ),
        sa.ForeignKeyConstraint(
            ["usuario_id"],
            ["usuarios.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("usuario_id", "empresa_id", name="uq_usuario_empresa"),
    )
    with op.batch_alter_table("usuarios_empresas", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_usuarios_empresas_empresa_id"), ["empresa_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_usuarios_empresas_usuario_id"), ["usuario_id"], unique=False
        )

    op.create_table(
        "centros_custo",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("ecd_id", sa.Integer(), nullable=False),
        sa.Column("cod_ccus", sa.String(length=255), nullable=False),
        sa.Column("ccus", sa.String(length=255), nullable=False),
        sa.Column("dt_alt", sa.Date(), nullable=True),
        sa.ForeignKeyConstraint(
            ["ecd_id"],
            ["ecds.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("ecd_id", "cod_ccus", name="uq_centro_custo_ecd"),
    )
    with op.batch_alter_table("centros_custo", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_centros_custo_cod_ccus"), ["cod_ccus"], unique=False)
        batch_op.create_index(batch_op.f("ix_centros_custo_ecd_id"), ["ecd_id"], unique=False)

    op.create_table(
        "historicos_padrao",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("ecd_id", sa.Integer(), nullable=False),
        sa.Column("cod_hist", sa.String(length=255), nullable=False),
        sa.Column("descr_hist", sa.String(length=255), nullable=False),
        sa.ForeignKeyConstraint(
            ["ecd_id"],
            ["ecds.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("historicos_padrao", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_historicos_padrao_ecd_id"), ["ecd_id"], unique=False)

    op.create_table(
        "lancamentos",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("ecd_id", sa.Integer(), nullable=False),
        sa.Column("num_lcto", sa.String(length=255), nullable=False),
        sa.Column("dt_lcto", sa.Date(), nullable=False),
        sa.Column("vl_lcto", sa.Float(), nullable=False),
        sa.Column("ind_lcto", sa.String(length=1), nullable=False),
        sa.Column("num_arq", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["ecd_id"],
            ["ecds.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("ecd_id", "num_lcto", "dt_lcto", name="uq_lancamento_ecd"),
    )
    with op.batch_alter_table("lancamentos", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_lancamentos_dt_lcto"), ["dt_lcto"], unique=False)
        batch_op.create_index(batch_op.f("ix_lancamentos_ecd_id"), ["ecd_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_lancamentos_num_lcto"), ["num_lcto"], unique=False)

    op.create_table(
        "participantes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("ecd_id", sa.Integer(), nullable=False),
        sa.Column("cod_part", sa.String(length=255), nullable=False),
        sa.Column("nome", sa.String(length=150), nullable=False),
        sa.Column("cnpj", sa.String(length=14), nullable=True),
        sa.Column("cpf", sa.String(length=11), nullable=True),
        sa.ForeignKeyConstraint(
            ["ecd_id"],
            ["ecds.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("ecd_id", "cod_part", name="uq_participante_ecd"),
    )
    with op.batch_alter_table("participantes", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_participantes_cod_part"), ["cod_part"], unique=False)
        batch_op.create_index(batch_op.f("ix_participantes_ecd_id"), ["ecd_id"], unique=False)

    op.create_table(
        "plano_contas",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("ecd_id", sa.Integer(), nullable=False),
        sa.Column("cod_cta", sa.String(length=255), nullable=False),
        sa.Column("cod_cta_sup", sa.String(length=255), nullable=True),
        sa.Column("nome_cta", sa.String(length=255), nullable=False),
        sa.Column("cod_nat", sa.String(length=2), nullable=False),
        sa.Column("ind_cta", sa.String(length=1), nullable=False),
        sa.Column("nivel", sa.Integer(), nullable=False),
        sa.Column("dt_alt", sa.Date(), nullable=True),
        sa.ForeignKeyConstraint(
            ["ecd_id"],
            ["ecds.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("ecd_id", "cod_cta", name="uq_plano_conta_ecd"),
    )
    with op.batch_alter_table("plano_contas", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_plano_contas_cod_cta"), ["cod_cta"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_plano_contas_cod_cta_sup"), ["cod_cta_sup"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_plano_contas_ecd_id"), ["ecd_id"], unique=False)

    op.create_table(
        "saldos_periodicos",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("ecd_id", sa.Integer(), nullable=False),
        sa.Column("cod_cta", sa.String(length=255), nullable=False),
        sa.Column("cod_ccus", sa.String(length=255), nullable=True),
        sa.Column("dt_ini", sa.Date(), nullable=False),
        sa.Column("dt_fin", sa.Date(), nullable=False),
        sa.Column("vl_sld_ini", sa.Float(), nullable=False),
        sa.Column("ind_dc_ini", sa.String(length=1), nullable=False),
        sa.Column("vl_deb", sa.Float(), nullable=False),
        sa.Column("vl_cred", sa.Float(), nullable=False),
        sa.Column("vl_sld_fin", sa.Float(), nullable=False),
        sa.Column("ind_dc_fin", sa.String(length=1), nullable=False),
        sa.ForeignKeyConstraint(
            ["ecd_id"],
            ["ecds.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "ecd_id", "cod_cta", "cod_ccus", "dt_ini", "dt_fin", name="uq_saldo_periodico"
        ),
    )
    with op.batch_alter_table("saldos_periodicos", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_saldos_periodicos_cod_cta"), ["cod_cta"], unique=False)
        batch_op.create_index(batch_op.f("ix_saldos_periodicos_ecd_id"), ["ecd_id"], unique=False)

    op.create_table(
        "saldos_resultado",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("ecd_id", sa.Integer(), nullable=False),
        sa.Column("cod_cta", sa.String(length=255), nullable=False),
        sa.Column("cod_ccus", sa.String(length=255), nullable=True),
        sa.Column("dt_res", sa.Date(), nullable=False),
        sa.Column("vl_sld_fin", sa.Float(), nullable=False),
        sa.Column("ind_dc_fin", sa.String(length=1), nullable=False),
        sa.ForeignKeyConstraint(
            ["ecd_id"],
            ["ecds.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("ecd_id", "cod_cta", "cod_ccus", "dt_res", name="uq_saldo_resultado"),
    )
    with op.batch_alter_table("saldos_resultado", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_saldos_resultado_cod_cta"), ["cod_cta"], unique=False)
        batch_op.create_index(batch_op.f("ix_saldos_resultado_ecd_id"), ["ecd_id"], unique=False)

    op.create_table(
        "aglutinacoes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("plano_conta_id", sa.Integer(), nullable=False),
        sa.Column("cod_ccus", sa.String(length=255), nullable=True),
        sa.Column("cod_agl", sa.String(length=255), nullable=False),
        sa.ForeignKeyConstraint(
            ["plano_conta_id"],
            ["plano_contas.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("aglutinacoes", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_aglutinacoes_cod_agl"), ["cod_agl"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_aglutinacoes_plano_conta_id"), ["plano_conta_id"], unique=False
        )

    op.create_table(
        "contas_referenciais",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("plano_conta_id", sa.Integer(), nullable=False),
        sa.Column("cod_ccus", sa.String(length=255), nullable=True),
        sa.Column("cod_cta_ref", sa.String(length=255), nullable=False),
        sa.ForeignKeyConstraint(
            ["plano_conta_id"],
            ["plano_contas.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("contas_referenciais", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_contas_referenciais_plano_conta_id"), ["plano_conta_id"], unique=False
        )

    op.create_table(
        "partidas",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("lancamento_id", sa.Integer(), nullable=False),
        sa.Column("cod_cta", sa.String(length=255), nullable=False),
        sa.Column("cod_ccus", sa.String(length=255), nullable=True),
        sa.Column("vl_dc", sa.Float(), nullable=False),
        sa.Column("ind_dc", sa.String(length=1), nullable=False),
        sa.Column("num_arq", sa.Integer(), nullable=True),
        sa.Column("cod_hist_pad", sa.String(length=255), nullable=True),
        sa.Column("hist", sa.Text(), nullable=True),
        sa.Column("cod_part", sa.String(length=255), nullable=True),
        sa.ForeignKeyConstraint(
            ["lancamento_id"],
            ["lancamentos.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("partidas", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_partidas_cod_cta"), ["cod_cta"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_partidas_lancamento_id"), ["lancamento_id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("partidas", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_partidas_lancamento_id"))
        batch_op.drop_index(batch_op.f("ix_partidas_cod_cta"))

    op.drop_table("partidas")
    with op.batch_alter_table("contas_referenciais", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_contas_referenciais_plano_conta_id"))

    op.drop_table("contas_referenciais")
    with op.batch_alter_table("aglutinacoes", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_aglutinacoes_plano_conta_id"))
        batch_op.drop_index(batch_op.f("ix_aglutinacoes_cod_agl"))

    op.drop_table("aglutinacoes")
    with op.batch_alter_table("saldos_resultado", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_saldos_resultado_ecd_id"))
        batch_op.drop_index(batch_op.f("ix_saldos_resultado_cod_cta"))

    op.drop_table("saldos_resultado")
    with op.batch_alter_table("saldos_periodicos", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_saldos_periodicos_ecd_id"))
        batch_op.drop_index(batch_op.f("ix_saldos_periodicos_cod_cta"))

    op.drop_table("saldos_periodicos")
    with op.batch_alter_table("plano_contas", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_plano_contas_ecd_id"))
        batch_op.drop_index(batch_op.f("ix_plano_contas_cod_cta_sup"))
        batch_op.drop_index(batch_op.f("ix_plano_contas_cod_cta"))

    op.drop_table("plano_contas")
    with op.batch_alter_table("participantes", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_participantes_ecd_id"))
        batch_op.drop_index(batch_op.f("ix_participantes_cod_part"))

    op.drop_table("participantes")
    with op.batch_alter_table("lancamentos", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_lancamentos_num_lcto"))
        batch_op.drop_index(batch_op.f("ix_lancamentos_ecd_id"))
        batch_op.drop_index(batch_op.f("ix_lancamentos_dt_lcto"))

    op.drop_table("lancamentos")
    with op.batch_alter_table("historicos_padrao", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_historicos_padrao_ecd_id"))

    op.drop_table("historicos_padrao")
    with op.batch_alter_table("centros_custo", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_centros_custo_ecd_id"))
        batch_op.drop_index(batch_op.f("ix_centros_custo_cod_ccus"))

    op.drop_table("centros_custo")
    with op.batch_alter_table("usuarios_empresas", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_usuarios_empresas_usuario_id"))
        batch_op.drop_index(batch_op.f("ix_usuarios_empresas_empresa_id"))

    op.drop_table("usuarios_empresas")
    with op.batch_alter_table("sessoes", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_sessoes_usuario_id"))
        batch_op.drop_index(batch_op.f("ix_sessoes_token"))

    op.drop_table("sessoes")
    with op.batch_alter_table("mapeamentos", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_mapeamentos_empresa_id"))

    op.drop_table("mapeamentos")
    with op.batch_alter_table("ecds", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_ecds_empresa_id"))

    op.drop_table("ecds")
    with op.batch_alter_table("webhook_deliveries", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_webhook_deliveries_webhook_id"))
        batch_op.drop_index(batch_op.f("ix_webhook_deliveries_evento"))

    op.drop_table("webhook_deliveries")
    with op.batch_alter_table("usuarios", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_usuarios_escritorio_id"))
        batch_op.drop_index(batch_op.f("ix_usuarios_email"))

    op.drop_table("usuarios")
    with op.batch_alter_table("rate_limit_configs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_rate_limit_configs_api_key_id"))

    op.drop_table("rate_limit_configs")
    with op.batch_alter_table("empresas", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_empresas_escritorio_id"))
        batch_op.drop_index(batch_op.f("ix_empresas_cnpj"))

    op.drop_table("empresas")
    op.drop_table("webhooks")
    op.drop_table("filter_views")
    with op.batch_alter_table("escritorios", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_escritorios_slug"))

    op.drop_table("escritorios")
    with op.batch_alter_table("audit_logs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_audit_logs_usuario_id"))
        batch_op.drop_index(batch_op.f("ix_audit_logs_criado_em"))
        batch_op.drop_index(batch_op.f("ix_audit_logs_api_key_id"))
        batch_op.drop_index(batch_op.f("ix_audit_logs_acao"))

    op.drop_table("audit_logs")
    with op.batch_alter_table("async_jobs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_async_jobs_tipo"))
        batch_op.drop_index(batch_op.f("ix_async_jobs_status"))
        batch_op.drop_index(batch_op.f("ix_async_jobs_criado_em"))

    op.drop_table("async_jobs")
    with op.batch_alter_table("api_keys", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_api_keys_key_hash"))

    op.drop_table("api_keys")
    # ### end Alembic commands ###
